version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_DATABASE: 'tastyhub'
      MYSQL_ROOT_PASSWORD: 'password'  # Set root password here
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  app:
    build: .
    container_name: tastyhub
    restart: always
    depends_on:
      - db
    ports:
      - "5000:5000"
    
volumes:
  mysql_data:
